docker:
	docker build . -t "807158446417.dkr.ecr.us-west-2.amazonaws.com/test-app:1"
	docker push "807158446417.dkr.ecr.us-west-2.amazonaws.com/test-app:1"
	docker build . -t "807158446417.dkr.ecr.us-west-2.amazonaws.com/test-missing:0"
	docker push "807158446417.dkr.ecr.us-west-2.amazonaws.com/test-missing:0"