# permissions for end users to view ingressrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressrequest-viewer-role
rules:
- apiGroups:
  - k11n.dev
  resources:
  - ingressrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - ingressrequests/status
  verbs:
  - get
