apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: konstellation-manager
  name: kon-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: konstellation
  namespace: kon-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
  namespace: kon-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: konstellation
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - appconfigs
  - appreleases
  - apptargets
  - builds
  - ingressrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - appreleases
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - appreleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k11n.dev
  resources:
  - apps
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - apps
  - apptargets
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - apps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k11n.dev
  resources:
  - apptargets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k11n.dev
  resources:
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - builds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k11n.dev
  resources:
  - certificaterefs
  - ingressrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - clusterconfigs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - clusterconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k11n.dev
  resources:
  - ingressrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k11n.dev
  resources:
  - nodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - nodepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  - prometheusrules
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - gateways
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace: kon-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: konstellation
  namespace: kon-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: konstellation-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: konstellation
subjects:
- kind: ServiceAccount
  name: konstellation
  namespace: kon-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: konstellation-manager
  name: konstellation
  namespace: kon-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: konstellation-manager
  template:
    metadata:
      labels:
        control-plane: konstellation-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        image: k11n/operator:0.5.11
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: konstellation
      terminationGracePeriodSeconds: 10
