{
 "title": "App Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app", "query": "istio_requests_total" },
   { "name": "target", "query": "istio_requests_total" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods by release",
   "type": "graph",
   "description": "Number of pods by release",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_release:kon_running_pods:rate5m{namespace=\"${target}\", release=~\"${app}-\\\\d{8}.*\"}) by (release)",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Requests by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(destination_service_response_code:istio_requests_total:irate5m{destination_service=\"${app}.${target}.svc.cluster.local\", response_code=\"200\"}) / sum(destination_service_response_code:istio_requests_total:irate5m{destination_service=\"${app}.${target}.svc.cluster.local\", response_code!=\"0\"})",
     "legendFormat": "success rate"
    },
    {
     "expr": "sum(destination_service_response_code:istio_requests_total:irate5m{destination_service=\"${app}.${target}.svc.cluster.local\", response_code!=\"0\"})",
     "legendFormat": "total"
    },
    {
     "expr": "destination_service_response_code:istio_requests_total:irate5m{destination_service=\"${app}.${target}.svc.cluster.local\", response_code!=\"0\"}",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(namespace_pod_container:container_cpu_usage_seconds_total:rate5m{namespace=\"${target}\", pod=~\"${app}-\\\\d{8}.*\", container!=\"istio-proxy\"})",
     "legendFormat": "cores used"
    },
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:rate5m{namespace=\"${target}\", pod=~\"${app}-\\\\d{8}.*\", container!=\"istio-proxy\"})/ sum(namespace_pod_container:kube_pod_container_resource_requests_cpu_cores{namespace=\"${target}\", pod=~\"${app}-\\\\d{8}.*\", container!=\"istio-proxy\"})",
     "legendFormat": "% utilization"
    },
    {
     "expr": "max(namespace_pod_container:kube_pod_container_resource_requests_cpu_cores{namespace=\"${target}\", pod=~\"${app}-\\\\d{8}.*\", container!=\"istio-proxy\"})",
     "legendFormat": "cores requested"
    },
    {
     "expr": "max(namespace_pod_container:kube_pod_container_resource_limits_cpu_cores{namespace=\"${target}\", pod=~\"${app}-\\\\d{8}.*\", container!=\"istio-proxy\"})",
     "legendFormat": "cores limit"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "description": "Memory usage by release",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(label_replace(\n\tnamespace_pod_container:container_memory_working_set_bytes{namespace=\"${target}\", container!=\"istio-proxy\", pod=~\"${app}-\\\\d{8}.*\"},\n\t\"release\", \"$1\", \"pod\", \"([a-zA-Z0-9-]+-[0-9]+-[0-9]+-[a-z0-9]+).+\")\n\t) by (release)",
     "legendFormat": "max use for {{release}}"
    },
    {
     "expr": "max(namespace_pod_container:kube_pod_container_resource_requests_memory_bytes{namespace=\"${target}\", container!=\"istio-proxy\", pod=~\"${app}-\\\\d{8}.*\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "max(namespace_pod_container:kube_pod_container_resource_limits_memory_bytes{namespace=\"${target}\", container!=\"istio-proxy\", pod=~\"${app}-\\\\d{8}.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Inbound requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\n\tsum(destination_service_release_le:istio_request_duration_milliseconds_bucket:irate1m{\n\t\tdestination_service=\"${app}.${target}.svc.cluster.local\"}) by (le)\n)",
     "legendFormat": "tp50"
    },
    {
     "expr": "histogram_quantile(0.95,\n\tsum(destination_service_release_le:istio_request_duration_milliseconds_bucket:irate1m{\n\t\tdestination_service=\"${app}.${target}.svc.cluster.local\"}) by (le)\n)",
     "legendFormat": "tp95"
    },
    {
     "expr": "histogram_quantile(0.99,\n\tsum(destination_service_release_le:istio_request_duration_milliseconds_bucket:irate1m{\n\t\tdestination_service=\"${app}.${target}.svc.cluster.local\"}) by (le)\n)",
     "legendFormat": "tp99"
    }
   ]
  },
  {
   "title": "Avg request sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(destination_service_release_source:istio_request_bytes_sum:rate5m{destination_service=\"${app}.${target}.svc.cluster.local\"}) / \nsum(destination_service_release_source:istio_request_bytes_count:rate5m{destination_service=\"${app}.${target}.svc.cluster.local\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(destination_service_release_source:istio_response_bytes_sum:rate5m{destination_service=\"${app}.${target}.svc.cluster.local\"}) / \nsum(destination_service_release_source:istio_response_bytes_count:rate5m{destination_service=\"${app}.${target}.svc.cluster.local\"})",
     "legendFormat": "response"
    }
   ]
  },
  {
   "title": "Requests by source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(destination_service_source_release:istio_request_duration_milliseconds_count:irate1m{destination_service=\"${app}.${target}.svc.cluster.local\"}) by (source_app)",
     "legendFormat": "{{source_app}}"
    }
   ]
  },
  {
   "title": "Throughput by source",
   "type": "graph",
   "description": "Inbound bytes/s split by source",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(destination_service_release_source:istio_request_bytes_sum:rate5m{destination_service=\"${app}.${target}.svc.cluster.local\"}) by (source_app) + sum(destination_service_release_source:istio_response_bytes_sum:rate5m{destination_service=\"${app}.${target}.svc.cluster.local\"}) by (source_app)",
     "legendFormat": "{{source_app}}"
    }
   ]
  },
  {
   "title": "RPS per instance",
   "type": "graph",
   "description": "Requests per second per instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(destination_service_response_code:istio_requests_total:irate5m{destination_service=\"${app}.${target}.svc.cluster.local\", response_code!=\"0\"}) /\nsum(namespace_release:kon_running_pods:rate5m{namespace=\"${target}\", release=~\"${app}-\\\\d{8}-.*\"})",
     "legendFormat": "rps"
    }
   ]
  },
  { "title": "Outbound requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Requests by destination",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(app_target_release_destination:istio_response_bytes_count:rate5m{app=\"${app}\", k11n_dev_target=\"${target}\"}) by (destination_app)",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Throughput by destination",
   "type": "graph",
   "description": "Outbound bytes/s split by destination",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(app_target_release_destination:istio_request_bytes_sum:rate5m{app=\"${app}\", k11n_dev_target=\"${target}\"}) by (destination_app) + sum(app_target_release_destination:istio_response_bytes_sum:rate5m{app=\"${app}\", k11n_dev_target=\"${target}\"}) by (destination_app)",
     "legendFormat": "{{destination_app}}"
    }
   ]
  }
 ]
}