// Code generated by qtc from "kube_config.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line cli/templates/kube_config.qtpl:1
package templates

//line cli/templates/kube_config.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line cli/templates/kube_config.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line cli/templates/kube_config.qtpl:1
func StreamKubeConfig(qw422016 *qt422016.Writer, endpointUrl string, encodedCAData string, tokenCmd string, tokenArgs []string) {
//line cli/templates/kube_config.qtpl:1
	qw422016.N().S(`
apiVersion: v1
clusters:
- cluster:
    server: `)
//line cli/templates/kube_config.qtpl:5
	qw422016.E().S(endpointUrl)
//line cli/templates/kube_config.qtpl:5
	qw422016.N().S(`
    certificate-authority-data: `)
//line cli/templates/kube_config.qtpl:6
	qw422016.E().S(encodedCAData)
//line cli/templates/kube_config.qtpl:6
	qw422016.N().S(`
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: konstellation
  name: konstellation
current-context: konstellation
kind: Config
preferences: {}
users:
- name: konstellation
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: `)
//line cli/templates/kube_config.qtpl:21
	qw422016.E().S(tokenCmd)
//line cli/templates/kube_config.qtpl:21
	qw422016.N().S(`
      args:
`)
//line cli/templates/kube_config.qtpl:23
	for _, arg := range tokenArgs {
//line cli/templates/kube_config.qtpl:23
		qw422016.N().S(`      - "`)
//line cli/templates/kube_config.qtpl:24
		qw422016.E().S(arg)
//line cli/templates/kube_config.qtpl:24
		qw422016.N().S(`"
`)
//line cli/templates/kube_config.qtpl:25
	}
//line cli/templates/kube_config.qtpl:26
}

//line cli/templates/kube_config.qtpl:26
func WriteKubeConfig(qq422016 qtio422016.Writer, endpointUrl string, encodedCAData string, tokenCmd string, tokenArgs []string) {
//line cli/templates/kube_config.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line cli/templates/kube_config.qtpl:26
	StreamKubeConfig(qw422016, endpointUrl, encodedCAData, tokenCmd, tokenArgs)
//line cli/templates/kube_config.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line cli/templates/kube_config.qtpl:26
}

//line cli/templates/kube_config.qtpl:26
func KubeConfig(endpointUrl string, encodedCAData string, tokenCmd string, tokenArgs []string) string {
//line cli/templates/kube_config.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line cli/templates/kube_config.qtpl:26
	WriteKubeConfig(qb422016, endpointUrl, encodedCAData, tokenCmd, tokenArgs)
//line cli/templates/kube_config.qtpl:26
	qs422016 := string(qb422016.B)
//line cli/templates/kube_config.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line cli/templates/kube_config.qtpl:26
	return qs422016
//line cli/templates/kube_config.qtpl:26
}
